-- NOT NULL 
CREATE TABLE MyTable10(
	col1 VARCHAR(255),
    col2 VARCHAR(255) NOT NULL
);

DESC MyTable10;
INSERT INTO MyTable10 (col1, col2) VALUES ('a', 'b');
INSERT INTO MyTable10 (col2) VALUES ('c');
INSERT INTO MyTable10 (col1) VALUES ('d');

SELECT * FROM MyTable10;
DROP TABLE myTable10;

CREATE TABLE MyTable11(
	col1 INT,
    col2 INT NOT NULL
);

INSERT INTO MyTable11 (col1, col2) VALUES (3, 4);
INSERT INTO MyTable11 (col2) VALUES (4);
INSERT INTO MyTable11 (col1) VALUES (3);
SELECT * FROM MyTable11;
